pipeline {
    agent any

    stages {
        stage("test") {
            steps {
                sh "go test ./..."
            }
        }

        stage("build") {
            steps {
                echo 'building the application'
            }
        }

         stage("deploy") {
            steps {
                echo 'deploying the application'
            }
        }
    }
}