pipeline {
    agent {
        kubernetes {
            yamlFile './pod.yaml'
        }
    }

    stages {
        stage("test") {
            steps {
                container('golang') {
                    sh "go test ./..."
                }
            }
        }

        stage("build") {
            steps {
                echo 'building the application'
            }
        }

         stage("deploy") {
            steps {
                echo 'deploying the application'
            }
        }
    }
}