apiVersion: v1
kind: Pod
spec:
  containers:
    - name: golang
      image: golang:1.24-alpine # use golang container to run tests and build binaries
      command: ["cat"] # use cat to keep the container alive during jenkins build
      tty: true # required for cat